# Generated by Django 2.1.5 on 2020-02-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviebook', '0003_auto_20200206_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('rezie', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_zanru', models.CharField(max_length=80)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviebook.Film')),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
